// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MovieFinalProject.Models;

#nullable disable

namespace MovieFinalProject.Migrations
{
    [DbContext(typeof(MovieContext))]
    partial class MovieContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MovieFinalProject.Models.Genre", b =>
                {
                    b.Property<string>("GenreId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GenreId");

                    b.ToTable("Genres");

                    b.HasData(
                        new
                        {
                            GenreId = "A",
                            Name = "Action"
                        },
                        new
                        {
                            GenreId = "C",
                            Name = "Comedy"
                        },
                        new
                        {
                            GenreId = "D",
                            Name = "Drama"
                        },
                        new
                        {
                            GenreId = "H",
                            Name = "Horror"
                        },
                        new
                        {
                            GenreId = "M",
                            Name = "Musical"
                        },
                        new
                        {
                            GenreId = "R",
                            Name = "Romance"
                        },
                        new
                        {
                            GenreId = "S",
                            Name = "SciFi"
                        },
                        new
                        {
                            GenreId = "F",
                            Name = "Fantasy"
                        },
                        new
                        {
                            GenreId = "N",
                            Name = "Noir"
                        });
                });

            modelBuilder.Entity("MovieFinalProject.Models.Movie", b =>
                {
                    b.Property<int>("MovieId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MovieId"));

                    b.Property<string>("GenreId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Rating")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int?>("Year")
                        .IsRequired()
                        .HasColumnType("int");

                    b.HasKey("MovieId");

                    b.HasIndex("GenreId");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            MovieId = 1,
                            GenreId = "F",
                            Name = "My Neighbor Totoro",
                            Rating = 4,
                            Year = 1988
                        },
                        new
                        {
                            MovieId = 2,
                            GenreId = "R",
                            Name = "Your Name",
                            Rating = 4,
                            Year = 2016
                        },
                        new
                        {
                            MovieId = 3,
                            GenreId = "C",
                            Name = "Dodgeball",
                            Rating = 3,
                            Year = 2004
                        },
                        new
                        {
                            MovieId = 4,
                            GenreId = "C",
                            Name = "Pineapple Express",
                            Rating = 3,
                            Year = 2008
                        },
                        new
                        {
                            MovieId = 5,
                            GenreId = "R",
                            Name = "About Time",
                            Rating = 4,
                            Year = 2013
                        });
                });

            modelBuilder.Entity("MovieFinalProject.Models.Movie", b =>
                {
                    b.HasOne("MovieFinalProject.Models.Genre", "Genre")
                        .WithMany()
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Genre");
                });
#pragma warning restore 612, 618
        }
    }
}
